### PR TITLE
Add method sizeToFit() 

### PR DESCRIPTION
**Pull request by lucdion**
Add a method `sizeToFit()`. 
The method adjust the view's size based on the result of the method `UIView.sizeToFit()`

Example:
```
view.pin.center().sizeToFit()
```

### CODE REVIEW

**Comment by antoinelamy** [comment]
It would be nice to remove `sizeToFit()` in the `SizeCalculable` protocol, I made a mistake in putting it there.

**Comment by antoinelamy** [comment]
Or we can also leave it as is but I feel that there is a bit of repetition there since no view should override `sizeToFit()` but do so for `sizeThatFits()` instead.

**Comment by lucdion** [comment]
@antoinelamy I will keep it that way in this PR, but we have a discussion about this.

**Comment by cajurabi** [comment]
@lucdion @antoinelamy my 2cents would be to remove from the SizeCalculable protocol for UIKit consistency.  Thanks for the great work on PinLayout and FlexLayout.

**Pull request merged**
